# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-19 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
        ),
    ]
